source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSToastView_Example', :exclusive => true do
  pod "NSToastView", :path => "../"
end

target 'NSToastView_Tests', :exclusive => true do
  pod "NSToastView", :path => "../"

  pod 'FBSnapshotTestCase'
end
